name: .NET

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: |
            6.0.x
            7.0.x
            8.0.x

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish WebFormsCore
        uses: GerardSmit/publish-nuget@v3.1.2
        with:
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          VERSION_FILE_PATH: Directory.Build.props
          PROJECT_FILE_PATH: |
            src/WebFormsCore/WebFormsCore.csproj
            src/WebFormsCore.Parser/WebFormsCore.Parser.csproj
            src/WebFormsCore.Compiler/WebFormsCore.Compiler.csproj
            src/WebFormsCore.SourceGenerator/WebFormsCore.SourceGenerator.csproj
            sdk/WebFormsCore.SDK/WebFormsCore.SDK.csproj
            sdk/WebFormsCore.SDK.AspNet/WebFormsCore.SDK.AspNet.csproj
            sdk/WebFormsCore.SDK.AspNetCore/WebFormsCore.SDK.AspNetCore.csproj
            src/WebFormsCore.Extensions.Choices/WebFormsCore.Extensions.Choices.csproj
            src/WebFormsCore.Extensions.ClientResourceManagement/WebFormsCore.Extensions.ClientResourceManagement.csproj
            src/WebFormsCore.Extensions.EntityFrameworkCore/WebFormsCore.Extensions.EntityFrameworkCore.csproj
            src/WebFormsCore.Extensions.Grid/WebFormsCore.Extensions.Grid.csproj
            src/WebFormsCore.Extensions.TinyMCE/WebFormsCore.Extensions.TinyMCE.csproj
